# Generated by Django 5.1.2 on 2024-10-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='owner_id',
        ),
    ]
